receivers:
    awsecscontainermetrics:
  
exporters:
  logging:
    loglevel: debug
  file:
    path: ./metrics_result.json
  
service:
  pipelines:
    metrics:
      receivers: [awsecscontainermetrics]
      exporters: [logging, file]
  